"""initial migration

Revision ID: 0001
Revises: 
Create Date: 2026-03-06 18:51:19.930549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('_password', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='lexnorm'
    )
    op.create_index(op.f('ix_lexnorm_authentications_email'), 'authentications', ['email'], unique=True, schema='lexnorm')
    op.create_index(op.f('ix_lexnorm_authentications_id'), 'authentications', ['id'], unique=False, schema='lexnorm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lexnorm_authentications_id'), table_name='authentications', schema='lexnorm')
    op.drop_index(op.f('ix_lexnorm_authentications_email'), table_name='authentications', schema='lexnorm')
    op.drop_table('authentications', schema='lexnorm')
    # ### end Alembic commands ###
